#!/bin/bash

name=$1
compile_command="g++ -o $name $name.cpp -std=c++11 -lm -O2"
main_content="#include <iostream>\r\rusing namespace std;\r\rint main() {\r\treturn 0;\r}\r"
file_ext="cpp"
while test $# -gt 0
do
    case "$1" in
        -c) compile_command="gcc -o $name $name.c -lm -O2"
             main_content="#include <stdio.h>\r\rint main() {\r\treturn 0;\r}\r"
             file_ext="c"
            ;;
        *)
            ;;
    esac
    shift
done

mkdir $name
echo -e $main_content >> ./$name/$name.$file_ext

touch ./$name/$name.in.txt
touch ./$name/$name.out.txt
touch ./$name/result.txt
touch ./$name/notes.txt

touch ./$name/makefile
echo -e "$compile_command
./$name < $name.in > result.txt
diff -c result.txt $name.out
" >> ./$name/makefile

touch ./$name/run
echo -e "$compile_command
./$name < $name.in" >> ./$name/run
